window.FINOPS_DEMO_SESSIONS = [
  { session_id_hash: "a12f…91c0", agent_id_hash: "agent-a", team_id: "platform", source: "codex", model: "gpt-5", decision: "new_task", n_prompts: 31, tokens_billed: 184200, context_pct: 0.91, cost_usd: 8.74, boundary_age_prompts: 11, days_ago: 1 },
  { session_id_hash: "77bc…e120", agent_id_hash: "agent-b", team_id: "product", source: "claude_code", model: "sonnet", decision: "continuation", n_prompts: 18, tokens_billed: 91200, context_pct: 0.57, cost_usd: 4.18, boundary_age_prompts: 0, days_ago: 1 },
  { session_id_hash: "cc31…a9d4", agent_id_hash: "agent-c", team_id: "security", source: "gemini", model: "pro", decision: "task_complete", n_prompts: 14, tokens_billed: 68800, context_pct: 0.43, cost_usd: 2.67, boundary_age_prompts: 0, days_ago: 2 },
  { session_id_hash: "2b0e…774a", agent_id_hash: "agent-d", team_id: "platform", source: "codex", model: "gpt-5", decision: "new_task", n_prompts: 27, tokens_billed: 153400, context_pct: 0.84, cost_usd: 7.11, boundary_age_prompts: 8, days_ago: 3 },
  { session_id_hash: "98da…12f7", agent_id_hash: "agent-e", team_id: "research", source: "claude_code", model: "sonnet", decision: "unclear", n_prompts: 9, tokens_billed: 45600, context_pct: 0.32, cost_usd: 1.88, boundary_age_prompts: null, days_ago: 4 },
  { session_id_hash: "6fe3…bd52", agent_id_hash: "agent-f", team_id: "product", source: "codex", model: "gpt-5", decision: "continuation", n_prompts: 22, tokens_billed: 117700, context_pct: 0.68, cost_usd: 5.36, boundary_age_prompts: 0, days_ago: 6 },
  { session_id_hash: "b479…300c", agent_id_hash: "agent-a", team_id: "platform", source: "codex", model: "gpt-5", decision: "task_complete", n_prompts: 16, tokens_billed: 73400, context_pct: 0.49, cost_usd: 3.21, boundary_age_prompts: 0, days_ago: 9 },
  { session_id_hash: "d802…fa11", agent_id_hash: "agent-g", team_id: "security", source: "claude_code", model: "sonnet", decision: "new_task", n_prompts: 35, tokens_billed: 209100, context_pct: 0.96, cost_usd: 10.42, boundary_age_prompts: 14, days_ago: 12 },
  { session_id_hash: "4ca8…194e", agent_id_hash: "agent-h", team_id: "research", source: "gemini", model: "pro", decision: "continuation", n_prompts: 12, tokens_billed: 59200, context_pct: 0.38, cost_usd: 2.31, boundary_age_prompts: 0, days_ago: 15 },
  { session_id_hash: "e17b…02aa", agent_id_hash: "agent-i", team_id: "product", source: "codex", model: "gpt-5", decision: "new_task", n_prompts: 29, tokens_billed: 166300, context_pct: 0.88, cost_usd: 7.83, boundary_age_prompts: 9, days_ago: 19 },
  { session_id_hash: "39d5…7c81", agent_id_hash: "agent-j", team_id: "security", source: "gemini", model: "pro", decision: "fresh", n_prompts: 3, tokens_billed: 12100, context_pct: 0.08, cost_usd: 0.41, boundary_age_prompts: 0, days_ago: 24 },
  { session_id_hash: "aa90…662d", agent_id_hash: "agent-b", team_id: "product", source: "claude_code", model: "sonnet", decision: "task_complete", n_prompts: 20, tokens_billed: 103800, context_pct: 0.63, cost_usd: 4.72, boundary_age_prompts: 0, days_ago: 28 },
  { session_id_hash: "0f44…ac93", agent_id_hash: "agent-k", team_id: "research", source: "codex", model: "gpt-5", decision: "new_task", n_prompts: 33, tokens_billed: 198600, context_pct: 0.93, cost_usd: 9.56, boundary_age_prompts: 12, days_ago: 44 },
  { session_id_hash: "71ea…ed08", agent_id_hash: "agent-l", team_id: "platform", source: "gemini", model: "pro", decision: "continuation", n_prompts: 17, tokens_billed: 84200, context_pct: 0.54, cost_usd: 3.08, boundary_age_prompts: 0, days_ago: 61 }
];
